  - name: Install nano
    yum: name={{ item }} state=present
    with_items:
      - nano
      - git

  - name: Get github nanorc/nanorc
    git: repo=https://github.com/nanorc/nanorc
         dest=/tmp/nano

  - name: make .nano
    command: make install 
             chdir=/tmp/nano
             creates=~/.nano

  - name: make nanorc
    copy: src=nanorc dest=~/.nanorc owner=root group=root mode=0644

  - name: What version of git do we have?
    shell: rpm -q nano|cut -d- -f2
    register: nano_version

  - name: Bind keys
    lineinfile: dest=~/.nanorc regexp="{{ item.regexp }}" line="{{ item.line }}"
    when: "{{ nano_version.stdout | version_compare('2.1', '>=', strict=True) }}"
    with_items:
      - { regexp: '^bind F11', line: 'bind F11 copytext main' }
      - { regexp: '^bind F12', line: 'bind F12 mark main' }
